name: Sync Forks - OrderForce-Intelligence

run-name: Sync Forks - OrderForce-Intelligence

on:
  schedule:
    - cron: "0 0 * * *" # Run every day at 0:00 AM
  workflow_dispatch: # Manual dispatch

permissions:
  contents: write

env:
  GH_TOKEN: ${{ secrets.GH_PAT }}

defaults:
  run:
    shell: bash
    working-directory: ./scripts

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  sync-forks:
    name: Sync Forks
    runs-on: [self-hosted, Linux, ARM64, OrderForce-Intelligence, runner-1]
    
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      
      - name: Configure git
        run: |
          git config --global user.name "github-actions[OrderForce-Intelligence-bot]"
          git config --global user.email "github-actions[OrderForce-Intelligence-bot]@users.noreply.github.com"
      
      - name: Run script sync-forks
        run: echo "OrderForce-Intelligence" | ./sync-forks.sh
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
